from . import res_partner
from . import hr_employee
from . import clinic_specialty
from . import clinic_patient
from . import clinic_person_link
from . import clinic_health_insurance
from . import clinic_billing_route
from . import clinic_insurance_route
from . import clinic_practice
from . import clinic_patient_coverage
from . import clinic_tariff
from . import clinic_bond_system
from . import clinic_copayment
from . import clinic_practice_code_os
from . import clinic_practitioner_role
from . import clinic_practitioner_practice
from . import clinic_appointment
from . import clinic_dashboard
